[pytest]
DJANGO_SETTINGS_MODULE = app.settings
python_files = tests.py test_*.py *_tests.py
testpaths = source
addopts =
    --reuse-db
    --nomigrations
    --tb=no
    -q
    --no-header
    --strict-markers
    -W ignore::DeprecationWarning
markers =
    slow: marks tests as slow (deselect with '-m "not slow"')
    integration: marks tests as integration tests
    unit: marks tests as unit tests
