# Generated by Django 4.2.23 on 2025-07-24 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0004_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAddressState',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='email_state', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
