# Generated by Django 4.2.7 on 2025-07-24 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_emailaddressstate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailaddressstate',
            old_name='confirmed',
            new_name='is_confirmed',
        ),
        migrations.AddField(
            model_name='emailaddressstate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='emailaddressstate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
