# Generated by Django 4.2.23 on 2026-02-16 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_subscription_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('monthly', 'Monthly ($3.99/mo)'), ('yearly', 'Yearly ($29.99/yr)'), ('lifetime', 'Lifetime (Early Supporter)')], default='monthly', max_length=20),
        ),
    ]
