# Generated by Django 4.2.23 on 2026-07-01 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_add_lifetime_plan_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='code_claimed',
            field=models.BooleanField(default=True),
        ),
    ]
