# Generated by Django 4.2.23 on 2025-07-22 21:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stone',
            fields=[
                ('PK_stone', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, validators=[main.models.validate_no_whitespace])),
                ('description', models.TextField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='stones/')),
                ('color', models.CharField(default='#4CAF50', max_length=7)),
                ('shape', models.CharField(default='circle', max_length=20)),
                ('FK_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stones', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StoneMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='stonemoves/')),
                ('comment', models.TextField(blank=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('FK_stone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='main.stone')),
                ('FK_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stone_moves', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
