# Generated by Django 4.2.23 on 2025-07-23 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stone',
            name='distance_km',
            field=models.FloatField(default=0.0),
        ),
    ]
