# Generated by Django 4.2.7 on 2025-08-01 14:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_stone_distance_km'),
    ]

    operations = [
        migrations.AddField(
            model_name='stone',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
    ]
