# Generated by Django 4.2.7 on 2025-08-01 14:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_populate_stone_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stone',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
