# Generated by Django 4.2.7 on 2025-08-03 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_make_uuid_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoneScanAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_time', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('FK_stone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_attempts', to='main.stone')),
                ('FK_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stone_scan_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['FK_stone', 'FK_user', 'scan_time'], name='main_stones_FK_ston_fba83e_idx')],
                'unique_together': {('FK_stone', 'FK_user')},
            },
        ),
    ]
