# Generated by Django 4.2.7 on 2025-08-03 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_stonescanattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='stone',
            name='stone_type',
            field=models.CharField(choices=[('hidden', 'Hidden'), ('hunted', 'Hunted')], default='hidden', max_length=20),
        ),
    ]
