# Generated by Django 4.2.7 on 2025-12-16 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_stone_stone_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='stone',
            name='qr_code_url',
            field=models.URLField(blank=True, help_text='Persistent QR code URL'),
        ),
        migrations.AddField(
            model_name='stone',
            name='sent_off_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stone',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('sent_off', 'Sent Off')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='stone',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
