# Generated by Django 4.2.7 on 2025-12-24 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0008_add_stone_status_and_qr_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='stone',
            name='claimed_at',
            field=models.DateTimeField(blank=True, help_text='When this stone was claimed by a user', null=True),
        ),
        migrations.AlterField(
            model_name='stone',
            name='FK_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stone',
            name='PK_stone',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, validators=[main.models.validate_no_whitespace]),
        ),
        migrations.AlterField(
            model_name='stone',
            name='status',
            field=models.CharField(choices=[('unclaimed', 'Unclaimed'), ('draft', 'Draft'), ('published', 'Published'), ('sent_off', 'Sent Off')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='QRPack',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pack_type', models.CharField(choices=[('free_single', 'Free Single QR'), ('paid_10pack', 'Paid 10-Pack')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Payment Pending'), ('paid', 'Paid'), ('fulfilled', 'Fulfilled'), ('failed', 'Payment Failed')], default='pending', max_length=20)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255, null=True)),
                ('price_cents', models.IntegerField(default=0, help_text='Price in cents')),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('pdf_generated', models.BooleanField(default=False)),
                ('download_count', models.IntegerField(default=0)),
                ('FK_user', models.ForeignKey(blank=True, help_text='User who purchased the pack', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qr_packs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='stone',
            name='FK_pack',
            field=models.ForeignKey(blank=True, help_text='QR pack this stone belongs to (if from shop)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stones', to='main.qrpack'),
        ),
    ]
