# Generated by Django 4.2.7 on 2026-02-17 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_sent_off_to_wandering'),
    ]

    operations = [
        migrations.AddField(
            model_name='stone',
            name='stone_number',
            field=models.PositiveIntegerField(blank=True, help_text='Sequential stone number, auto-assigned on creation', null=True, unique=True),
        ),
    ]
