# Generated by Django 4.2.23 on 2026-02-24 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_stone_stone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrpack',
            name='language',
            field=models.CharField(default='en', max_length=10),
        ),
    ]
