# Generated by Django 4.2.23 on 2026-07-01 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_qrpack_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='stonemove',
            name='is_confirmed',
            field=models.BooleanField(default=True),
        ),
    ]
